# Project information
site_name: Vion
site_url: https://lityuan0226.github.io/my-mkdocs/

# Copyright
copyright: Copyright &copy; 2025 Vionvision

  # Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - media: "{prefers-color-scheme}"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "{prefers-color-scheme: light}"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "{prefers-coloe-scheme: dark}"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

# Page tree
nav:
   - Home: index.md
   - Guide:
     - BI Platfrom: guide/bi-platform.md
     - Customer Operation SOP: guide/sop.md
     - On-Premises Server Hosting Guide: guide/hosting.md
     - Business Metrics Documentation: guide/metrics.md
     - Service Desk Operation Guide: guide/service.md
     - Configuration Guideline: guide/configuration.md
     - Senor Device Installation Guide: guide/device.md
     - Cbox Device Installation Guide: guide/cbox.md
     - RESTful API Documentation: guide/api.md
     - Integration: guide/integration.md
     - VionDeviceTool: guide/tool.md
   - Spec DataSheet:
     - G5: spec-datasheet/g5.md
     - CBox: spec-datasheet/cbox.md
     - BI v6: spec-datasheet/bi-v6.md
   - QuickGuide:
     - G5: quick-guide/g5.md
     - CBox: quick-guide/cbox.md
   - FAQ: faq.md
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
